### ISSUE TITLE
이미지가 사라지는 오류입니다

### ISSUE THREAD

**Issue by jinliuli** [Gwan-Woo-Jeong/Class-Resource-Downloader#1]
기존 이미지
![image](https://github.com/user-attachments/assets/f91fd6ad-a752-4410-885e-51d703c3a72f)

마우스 포인터를 이미지에 올렸을 때
![111image](https://github.com/user-attachments/assets/0429f193-29de-418b-ace7-886f6ea75fa3)

**Comment by Gwan-Woo-Jeong** [comment]
`<script>`안에 이벤트 핸들러가 이미지 경로를 변경하는 경우, 그 변경된 이미지 파일이 없거나 잘못된 주소로 연결되어 생기는 버그가 발견됐습니다. 스크립트가 참조하는 리소스를 모두 다운로드 하고 올바른 주소로 연결되게끔 수정하여 재배포하였습니다!
